language: nodejs
node_js:
  - 10
  
before_script:
  - npm install codecov -g
  - npm run setup
  - npm run build

script:
  - npm run test
  
after_success:
  - codecov
  
deploy:
  provider: releases
  file_glob: true
  file: dist/out-tsc/*
  skip_cleanup: true
  on:
    tags: true
